<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "news".
 *
 * @property int $idNews
 * @property string $nameNews
 * @property string $annotatio
 * @property string $contentNews
 * @property string $files
 * @property string $dateNews
 * @property int $cat_idCategory
 *
 * @property Commentsnews[] $commentsnews
 * @property Category $category
 */
class News extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'news';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nameNews', 'annotatio', 'contentNews', 'cat_idCategory'], 'required'],
            [['contentNews', 'files'], 'string'],
            [['dateNews'], 'date', 'format' => 'php:Y-m-d'],
            [['dateNews'], 'default', 'value' => date('Y-m-d')],
            [['cat_idCategory'], 'integer'],
            [['nameNews'], 'string', 'max' => 500],
            [['annotatio'], 'string', 'max' => 1000],
            [['cat_idCategory'], 'exist', 'skipOnError' => true, 'targetClass' => Category::className(), 'targetAttribute' => ['cat_idCategory' => 'idcategory']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'idNews' => 'Id News',
            'nameNews' => 'Name News',
            'annotatio' => 'Annotatio',
            'contentNews' => 'Content News',
            'files' => 'Files',
            'dateNews' => 'Date News',
            'cat_idCategory' => 'Id Category',
        ];
    }

    public function saveImage($filename)
    {
        $this->files = $filename;
        return $this->save(false);
    }

    /*
     * Удаление картинки если вся статья удалена
     */
    public function deleteImage()
    {
        $imageUploadModel = new ImageUpload();
        $imageUploadModel->deleteCurrentImage($this->files);
    }


    /*
     * Отображает картинку в листенге админа
     */
    public function getImage()
    {
        return ($this->files) ? 'uploads/' . $this->files : 'no-image.png';
    }

    /*
     * Вызов метода автоматческого удаления файла при удалении статьи
     */
    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }


//    /**
//     * @return \yii\db\ActiveQuery
//     */
//    public function getCommentsnews()
//    {
//        return $this->hasMany(Commentsnews::className(), ['idNews' => 'idnews']);
//    }
//
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['idcategory' => 'idCategory']);
    }
}
